# Generated by Django 6.0.3 on 2026-03-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='rol',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
