# Generated by Django 6.0.3 on 2026-04-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_evaluacion_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoSGSI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('DG', 'Documentos Generales'), ('CD', 'Control de Documentos'), ('VR', 'Valoración y Plan de Tratamiento de Riesgos'), ('CC', 'Concientización y Comunicación'), ('AI', 'Auditoría Interna'), ('AC', 'Acciones Correctivas y de Mejora'), ('RD', 'Revisión por la Dirección'), ('PS', 'Políticas de Seguridad'), ('OS', 'Organización de la Seguridad de la Información'), ('RH', 'Seguridad de los Recursos Humanos'), ('GA', 'Gestión de Activos'), ('CA', 'Control de Acceso'), ('EN', 'Encriptación'), ('SF', 'Seguridad Física y Ambiental'), ('SO', 'Seguridad en la Operación'), ('SC', 'Seguridad en las Comunicaciones'), ('AD', 'Adquisición, Desarrollo y Mantenimiento de Sistemas'), ('RP', 'Relación con Proveedores'), ('GI', 'Gestión de Incidentes de Seguridad'), ('CN', 'Continuidad del Negocio'), ('CU', 'Cumplimiento')], max_length=2)),
                ('ubicacion', models.CharField(default='/docs/', max_length=200)),
                ('ultima_revision', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['categoria', 'codigo'],
            },
        ),
    ]
